import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV generated by Zig
df = pd.read_csv("ecg_output.csv")

plt.figure(figsize=(12, 4))

# Plot filtered ECG
plt.plot(df["index"], df["filtered"], label="Filtered ECG", linewidth=1)

# Plot detected peaks
peaks = df[df["peak"] == 1]
plt.scatter(
    peaks["index"],
    peaks["filtered"],
    color="red",
    label="Detected R-peaks",
    zorder=3,
)

plt.title("Synthetic ECG with Detected R-peaks")
plt.xlabel("Sample Index")
plt.ylabel("Amplitude")
plt.legend()
plt.tight_layout()
plt.show()
